apiVersion: v1  #acts a manuall to your system
kind: Pod
metadata:  #like a tag
        name: mypod1
spec:
 containers:
    - name: mypod-co
      image: nginx:latest
      resources: 
          requests:
            cpu: "10m"
            memory: "12Mi"        
      ports:  
        - name: http
          containerPort: 80
          protocol: TCP





#units
#1 core  = 1000 millicoresb m = millicores
#1gb  = 1024mib's