apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pv-efs
      
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes: 
        - ReadWriteOnce

  storageClassName: standard  
  persistentVolumeReclaimPolicy: Retain
  csi:   #container storage type
    driver: efs.csi.aws.com
    volumeHandle: fs-0056605f16cc9289e
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  efs-claim

spec:  
 accessModes: 
  - ReadWriteOnce
storageClassName: standard
resources: 
   requests:
        storage: 5G 