apiVersion: v1
kind: PersistentVolume
metadata: 
      name: pv-efs
      
spec: 
    capacity:
      storage: 5Gi
      volumeMode: Filesystem
      accessModes: 
         - ReadWriteOnce

    storageClassName: standard  
    peristance
