apiVersion: v1
kind: ReplicationController
metadata:
      name: replicacontroller
      labels:
           app: replicatcontroller1
spec:
      replicas: 2
      template:
           metadata:
             name: replicatcontroller1
             