apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: replicaexists
      labels:
         app:  replicaexists
spec:
      replicas: 2
      template:
          metadata:
            name: replicaexists
            labels:
              app: replicaexists
          spec:
            containers:
              - image:  nginx:latest
                name: contexists
            resources:
            requests:
                 cpu: "10m"
                 memory: "12Mi"
            ports:
            - name:  http
              containerPort: 80
              protocol: TCP
      selector:
           matchExpressions:
             -  { key: app, operator: Exists}                
