apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: replicarmatchlable
     labels:
        app: replicamatchlable1
spec:
      replicas: 2
      template:
          metadata:
            name: replicamatchlable1
          labels:
               app: replicamatchlable1
          spec:
              containers:
                -      
