apiVersion: apps/v1
kind: ReplicaSet
metadata:
      name: replicanotin
      labels: 
          app: replicanotin
spec:
    replicas: 2
    template:
      #write here pod scriptfrom 
      metadata:
        name:  replicanotin
        labels:
           app: replicanotin
      spec:
          containers:
            - name:  contnotin
              image: nginx:latest
              resources:
                 requests:
                   cpu: "10m"
                   memory: "12Mi"
              ports:
                   - name: nginx:latest
                     port:  80
                     protocol: TCP 
    selector:
        matchExpressions:
            - {key: app, operator: notIn, values: [replicanotin1 , replicanotin2]}                       
            