apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: replicarmatchlable
     labels:
        app: replicamatchlable1
spec:
      replicas: 2
      template:
          metadata:
            name: replicamatchlable1
            labels:
               app: replicamatchlable1
          spec:
              containers:
                - name: contmatchlable
                  image:  nginx:latest
                  resources:
                      requests:
                        cpu: "10m"
                        memory: "12Mi"
                  ports:
                     - name:  http
                       containerPort: 80
                       protocol: TCP   
      selector:
             matchLabels:
                app: replicamatchlable1