apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: replicarmatchlable
     labels:
        app: replicamatchlable1
spec:
      replicas: 2
      apiVersion: v1
      kind: Secret
      metadata:
        name:  secretName
      data:
         secretKey:  BASE64_ENCODED_VALUE
      type: Opaque